#---
# Excerpted from "Ash Framework",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/ldash for more book information.
#---
# The final version of this file at the end of this chapter can be found at
# https://github.com/sevenseacat/tunez/blob/end-of-chapter-1/priv/repo/migrations/20250207064123_create_artists.exs

# ------------------------------------------------------------------------------
# Context: The migration generated by `ash.codegen` after setting up the Artist resource with attributes
def up do
  create table(:artists, primary_key: false) do
    add :id, :uuid, null: false, default: fragment("gen_random_uuid()"),
      primary_key: true
    add :name, :text, null: false
    add :biography, :text

    add :inserted_at, :utc_datetime_usec,
      null: false,
      default: fragment("(now() AT TIME ZONE 'utc')")

    add :updated_at, :utc_datetime_usec,
      null: false,
      default: fragment("(now() AT TIME ZONE 'utc')")
  end
end
# ------------------------------------------------------------------------------
