#---
# Excerpted from "Ash Framework",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/ldash for more book information.
#---
# The final version of this file at the end of this chapter can be found at
# https://github.com/sevenseacat/tunez/blob/end-of-chapter-2/priv/repo/migrations/20250101125618_add_unique_album_names_per_artist.exs

# ------------------------------------------------------------------------------
# Context: The autogenerated migration for adding the name/artist_id identity
def up do
  create unique_index(:albums, [:name, :artist_id],
            name: "albums_unique_album_names_per_artist_index"
          )
end

def down do
  drop_if_exists unique_index(:albums, [:name, :artist_id],
                    name: "albums_unique_album_names_per_artist_index"
                  )
end
# ------------------------------------------------------------------------------
